### ISSUE TITLE
Copy - purpose of the recursive flag?

### ISSUE THREAD

**Issue by BrianSilvia** [Brinkbit/http-fs-api#12]
The recursive flag doesn't seem to do anything for resources, only directories. But if it only applies to directories, shouldn't it be recursively inherently -- else it would just copy an empty directory?

**Comment by JustinLivi** [comment]
Recursive would be for subdirectories, but this may be the expected default behavior

**Comment by BrianSilvia** [comment]
So it would copy each resource in that directory, but any directories would be left empty after the copy? Or would they not be copied in the first place?

**Comment by BrianSilvia** [comment]
After with talking with @JustinLivi we decided that it makes the most sense to simply copy everything recursively, rather than 1) an empty top-level folder, or 2), the top-level folder, the children, but leaving any subdirectories empty. Thus, we're going to remove this flag and bake it into the action by default, when acting on a directory.
