### ISSUE TITLE
delete - recursive flag redundant

### ISSUE THREAD

**Issue by BrianSilvia** [Brinkbit/http-fs-api#15]
Deleting a resource doesn't utilize the recursive flag, and deleting a directory should delete all it's contents, else it will strand it's children.

**Comment by JustinLivi** [comment]
Deleting a resource with children without the recursive flag should throw an error

**Comment by BrianSilvia** [comment]
What's the purpose behind it? So the front-end can pop a dialogue box asking for confirmation? It's a flag that has no relevance for files, yet must be included for directories -- but if you're deleting a directory you're going to want to be doing it recursively.

**Comment by JustinLivi** [comment]
I think the original mentality here was mirroring unix

**Comment by JustinLivi** [comment]
And if by default you throw an error then you have the option

**Comment by BrianSilvia** [comment]
After discussion it with @JustinLivi, we're going to remove the recursive from delete, and bake the behavior into delete, when acting on a directory.
